-- ============================================================
-- Activity Mint — Carousel Feature Migration
-- Run once in Supabase SQL Editor
-- ============================================================

-- ── brand_dna ────────────────────────────────────────────────
-- Stores Claude-extracted brand analysis per (user, handle).
-- open-carrusel BrandConfig fields are the core; Activity Mint
-- voice/hook/pain fields extend it for richer slide generation.
create table if not exists brand_dna (
  id                  uuid        primary key default gen_random_uuid(),
  user_id             uuid        references auth.users not null,
  handle              text        not null,

  -- Visual identity (maps to open-carrusel BrandConfig.colors + fonts)
  brand_name          text,
  primary_color       text        not null default '#1a1a2e',
  secondary_color     text        not null default '#16213e',
  accent_color        text        not null default '#e94560',
  background_color    text        not null default '#ffffff',
  surface_color       text        not null default '#f5f5f5',
  heading_font        text        not null default 'Inter',
  body_font           text        not null default 'Inter',
  logo_url            text,
  style_keywords      text[]      not null default '{}',

  -- Brand voice (Activity Mint extension — from Claude tone analysis)
  voice_tone          text,
  voice_formality     int         check (voice_formality between 1 and 5),
  voice_energy        text        check (voice_energy in ('low', 'medium', 'high')),
  voice_personality   text[]      not null default '{}',
  emoji_density       text        check (emoji_density in ('none', 'light', 'heavy')),
  avg_caption_length  int,

  -- Performance patterns (from Hetzner post analysis)
  top_hooks           text[]      not null default '{}',
  audience_pains      text[]      not null default '{}',
  top_formats         text[]      not null default '{}',
  best_posting_hour   int         check (best_posting_hour between 0 and 23),

  -- Onboarding context
  niche               text,
  goal                text,
  customer_desc       text,

  extracted_at        timestamptz not null default now(),
  created_at          timestamptz not null default now(),

  unique (user_id, handle)
);

alter table brand_dna enable row level security;

create policy "Users read own brand_dna"
  on brand_dna for select
  using (auth.uid() = user_id);

create policy "Users upsert own brand_dna"
  on brand_dna for insert
  with check (auth.uid() = user_id);

create policy "Users update own brand_dna"
  on brand_dna for update
  using (auth.uid() = user_id);


-- ── carousels ────────────────────────────────────────────────
create table if not exists carousels (
  id              uuid        primary key default gen_random_uuid(),
  user_id         uuid        references auth.users not null,
  name            text        not null,
  aspect_ratio    text        not null default '4:5'
                  check (aspect_ratio in ('1:1', '4:5', '9:16')),
  template        text        check (template in ('listicle', 'myth', 'stats', 'steps', 'transform')),
  caption         text,
  hashtags        text[]      not null default '{}',
  brand_note      text,
  export_url      text,
  is_template     boolean     not null default false,
  tags            text[]      not null default '{}',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

alter table carousels enable row level security;

create policy "Users read own carousels"
  on carousels for select
  using (auth.uid() = user_id);

create policy "Users insert own carousels"
  on carousels for insert
  with check (auth.uid() = user_id);

create policy "Users update own carousels"
  on carousels for update
  using (auth.uid() = user_id);

create policy "Users delete own carousels"
  on carousels for delete
  using (auth.uid() = user_id);

-- Auto-update updated_at on every row change
create or replace function update_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger carousels_updated_at
  before update on carousels
  for each row execute function update_updated_at();


-- ── slides ───────────────────────────────────────────────────
-- Slides are body-level HTML blobs generated by Claude.
-- previous_versions stores up to 5 prior HTML strings for undo.
-- headline is extracted for the filmstrip thumbnail label.
create table if not exists slides (
  id                  uuid        primary key default gen_random_uuid(),
  carousel_id         uuid        references carousels(id) on delete cascade not null,
  html                text        not null,
  previous_versions   text[]      not null default '{}',
  slide_order         int         not null default 0,
  notes               text        not null default '',
  headline            text        not null default '',
  created_at          timestamptz not null default now()
);

create index slides_carousel_id_order
  on slides (carousel_id, slide_order);

alter table slides enable row level security;

-- Slides inherit access from their carousel (join check)
create policy "Users read slides of own carousels"
  on slides for select
  using (
    exists (
      select 1 from carousels
      where carousels.id = slides.carousel_id
        and carousels.user_id = auth.uid()
    )
  );

create policy "Users insert slides into own carousels"
  on slides for insert
  with check (
    exists (
      select 1 from carousels
      where carousels.id = slides.carousel_id
        and carousels.user_id = auth.uid()
    )
  );

create policy "Users update slides of own carousels"
  on slides for update
  using (
    exists (
      select 1 from carousels
      where carousels.id = slides.carousel_id
        and carousels.user_id = auth.uid()
    )
  );

create policy "Users delete slides from own carousels"
  on slides for delete
  using (
    exists (
      select 1 from carousels
      where carousels.id = slides.carousel_id
        and carousels.user_id = auth.uid()
    )
  );


-- ── style_presets (Phase 2 — create now, use later) ─────────
create table if not exists style_presets (
  id              uuid        primary key default gen_random_uuid(),
  user_id         uuid        references auth.users not null,
  name            text        not null,
  design_rules    text        not null,
  example_slide_html text,
  aspect_ratio    text        not null default '4:5',
  created_at      timestamptz not null default now()
);

alter table style_presets enable row level security;

create policy "Users manage own style_presets"
  on style_presets for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
